name: Build and Upload PDFs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the main (styrdokument) repository.
      - name: Checkout styrdokument repository
        uses: actions/checkout@v4

      # 2. Checkout the dTeX repository.
      - name: Checkout dTeX repository
        uses: actions/checkout@v4
        with:
          repository: SR-Gruppen/dTeX
          path: './dTeX'

      # 3. Copy dTeX class files and resources into a local "classes" folder.
      - name: Copy dTeX classes and resources
        run: |
          mkdir -p classes/ChS_FONTS
          cp dTeX/dtek.cls dTeX/dtekprotokoll.cls dTeX/dtekmotion.cls dTeX/dtekinstruktion.cls dTeX/dteklag.cls dTeX/dtekkallelse.cls dTeX/dteklogo.pdf dTeX/dteklogo_orange.pdf classes/

<<<<<<< HEAD
      - name: Compile PDFs
=======
      # 4. Compile documents in the repository root (using files in src/).
      - name: Compile PDFs
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            src/reglemente.tex
            src/stadgar.tex
            src/incidenthantering.tex
            src/instruktioner/*.tex
            src/riktlinjer/*.tex
            src/mallar/*.tex
            src/mallar/avtal/*.tex
            src/foreningar/date-it/*.tex
          work_in_root_file_dir: true
          latexmk_use_xelatex: true
          extra_fonts: |
            ./dTeX/ChS_FONTS/Open_Sans/*.ttf
            ./dTeX/ChS_FONTS/PT_Serif/*.ttf
        env:
          TEXINPUTS: ".:/github/workspace/classes//:"

      # 5. Compile documents in subdirectories. Note: We adjust TEXINPUTS relative path.
      - name: Compile instruktioner documents
>>>>>>> 2eeb431 (Does this fix fonts?)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            src/reglemente.tex
            src/stadgar.tex
            src/incidenthantering.tex
            src/instruktioner/*.tex
<<<<<<< HEAD
=======
          work_in_root_file_dir: true
          latexmk_use_xelatex: true
          extra_fonts: |
            ./dTeX/ChS_FONTS/Open_Sans/*.ttf
            ./dTeX/ChS_FONTS/PT_Serif/*.ttf
        env:
          TEXINPUTS: ".:../../classes//:"

      - name: Compile mallar documents
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            src/mallar/*.tex
          work_in_root_file_dir: true
          latexmk_use_xelatex: true
          extra_fonts: |
            ./dTeX/ChS_FONTS/Open_Sans/*.ttf
            ./dTeX/ChS_FONTS/PT_Serif/*.ttf
        env:
          TEXINPUTS: ".:../../classes//:"

      - name: Compile riktlinjer documents
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
>>>>>>> 2eeb431 (Does this fix fonts?)
            src/riktlinjer/*.tex
            src/mallar/*.tex
            src/mallar/avtal/*.tex
            src/foreningar/date-it/*.tex
          work_in_root_file_dir: true
          latexmk_use_xelatex: true
          extra_fonts: |
            ./dTeX/ChS_FONTS/Open_Sans/*.ttf
            ./dTeX/ChS_FONTS/PT_Serif/*.ttf
        env:
          TEXINPUTS: ".:${{ github.workspace }}/dTeX//:"
      - name: Clean up
        run: |
          rm -rf dTeX classes
          mv src/* .
          rm -rf src

<<<<<<< HEAD
=======
      - name: Compile foreningar documents
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            src/foreningar/*.tex
          work_in_root_file_dir: true
          latexmk_use_xelatex: true
          extra_fonts: |
            ./dTeX/ChS_FONTS/Open_Sans/*.ttf
            ./dTeX/ChS_FONTS/PT_Serif/*.ttf
        env:
          TEXINPUTS: ".:../../classes//:"

      # 6. Upload all generated PDFs as artifacts.
>>>>>>> 2eeb431 (Does this fix fonts?)
      - name: Upload PDF Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PDF-Artifacts
          path: "**/*.pdf"
